- src/Compat/CompatController.php
This will now only render the controls and footer if there's any content.
This is based on the assumption that an action has to define explicit
content if it wants to show controls or a footer. Even if the content
is populated by Javascript, there's usually another container part of
the content and the content is not directly utilized as target.
> CompatController: Allow to mix old-style actions with new-style ones

- src/Control/SearchBar/Suggestions.php
- src/Control/SearchBar/Terms.php
- src/Control/SearchEditor.php
blocked by https://github.com/Icinga/ipl-stdlib/pull/20
> Utilize native filter meta data instead of properties

- src/Compat/CompatController.php
Changes `CompatController::setTitle()` in a way that will inevitably lead to cases like this: (for unpatched usages)
> Introduce some new compat utils

- src/Control/SearchBar/ValidatedOperator.php
- src/Control/SearchEditor.php
- src/Filter/Parser.php
- src/Filter/QueryString.php
- src/Filter/Renderer.php
- tests/FilterTest.php
depends on icinga/ipl-stdlib#33
> Replace Filter::equal and Filter::unequal with Filter::similar and Filter::unlike correspondingly

- asset/css/balls.less
Just like `ok` or `up` state balls make `pending` state balls hollowed.
> Make `pending` state balls hollowed

- src/Compat/SearchControls.php
ipl-orm's column definitions are now "mature" enough for me to do this
> SearchControls: Provide base implementation for `fetchFilterColumns()`

- src/Control/SearchBar/Suggestions.php
The column path is also in the search bar labels the default, so why not here as well? Otherwise nothing is shown: `Search for *test* in:`
> Suggestions: Show column path in default if there's no label

- asset/css/primary-submit-btn-duplicate.less
- composer.json
- src/Compat/CompatForm.php
- tests/Compat/CompatFormTest.php
Creates a new `SubmitElement` from the primary submit button of the form with cloned Attributes from the given `FormSubmitElement`. The new submit button is always at the top of the form.
The element has a fixed `primary-submit-btn-duplicate` class, which hides to button, but not the functionality when submitting the form.
> CompatForm: Insert duplicate submit button when more than one is present

- src/Control/SearchBar.php
With the [recent changes](https://github.com/Icinga/ipl-html/pull/118) in ipl-html, `Form::validatePartial()` only validates elements with a value again. This results in the search bar not returning the filter transmitted by an autosubmit if the filter has been fully cleared by the user.
> SearchBar: Fix that `getFilter()` returns an outdated filter

- src/FormElement/ScheduleElement/AnnuallyFields.php
The `onRegistered()` mechanism works with `FieldsetElement` only when the fieldset is being used at the first level, i.e if the fieldset is added directly to the concrete `Form`. Otherwise, with such a nested `FieldsetElement` as the `AnnuallyFields`, this mechanism doesn't work as it is supposed to. Howeever, due to all the validation improvements made in `ipl-/html,validator,web`, this element doesn't even need to use that handler to work, so it's dropped.
> AnnuallyFields: Drop usage of `onRegistered()` handler

- src/Compat/CompatController.php
- src/Control/SortControl.php
This gives an option to set the default sort of sort control other than the `ipl\Orm\Model`s default sort as default.
> Add optional `$defaultSort` parameter for `SortControl::apply` method

- src/Compat/CompatForm.php
blocked by https://github.com/Icinga/ipl-html/pull/124
> CompatForm: Register form element namespace

- src/Control/SearchBar/ValidatedOperator.php
- src/Control/SearchBar/ValidatedTerm.php
An oversight. The label was always optional.
Also cleans up some type declarations which
were anything but correct.
> ValidatedTerm: Accept `null` as label

- src/Control/SearchBar/ValidatedTerm.php
- src/FormElement/TermInput/RegisteredTerm.php
The validation api validates an input's value, and if a label exists for a given term, it's used as value instead of the search value. Hence the pattern should check for the label, not the search value in such a case.
> Properly validate user input in term inputs and filter inputs

- src/Compat/CompatController.php
- src/Control/SortControl.php
> Process `POST` requests in `SortControl`

- asset/js/widget/TermInput.js
It's now controlled. Previously it depended on whether Enter is able to submit the form or not. But a submit isn't required either.
> TermInput.js: Also accept new terms upon pushing Enter

- src/Control/SortControl.php
> SortControl: Re-populate the control in case a partial match is found

- composer.json
- src/LessRuleset.php
- src/Style.php
- tests/LessRulesetTest.php
- tests/Lib/LessRulesetWithTestableRenderCss.php
- tests/Lib/StyleWithTestableRenderCss.php
- tests/Lib/TestableRenderCss.php
- tests/StyleTest.php
This PR introduces a new `Style` element to provide strict CSP compliant dynamic CSS when necessary.
**Note that it is still a work in progress, so it is not in the right namespace, is not documented, API is subject to change, and lacks unit tests.**
Example of creating style with some rulesets:
```
$style = new Style();
$style->add('.size', [
'height' => '1em',
'width'  => '1em'
]);
$style->add('.border', [
'border' => '1px solid black'
]);
```
Output:
```
<style>
.size {
height: 1em;
width: 1em;
}
.border {
border: 1px solid black;
}
</style>
```
Now we wrap the rules in a selector:
```
$style->setSelector('.parent');
```
Output:
```
<style>
.parent .size {
height: 1em;
width: 1em;
}
.parent .border {
border: 1px solid black;
}
</style>
```
We can also use LESS variables and nested …
> Introduce `Style` element

- asset/css/compat.less
- asset/css/controls.less
Any view using the default controls layout should have a thin search bar. Just like Icinga DB Web.
> css: Transfer icingadb related searchbar styles to default control layout

- src/Compat/CompatController.php
Test commit:https://github.com/Icinga/icingaweb2-module-reporting/pull/194
> Add different redirect options

- src/Control/SortControl.php
The previous condition only applied if the form's method was `POST` but not the request's. Essentially, if it was not being sent. Now it also applies if the form's method is `GET` but not the request's. (if another form is being sent)
fixes #199
> SortControl: Apply the url's parameter if the form is not sent

- .github/workflows/php.yml
- phpstan-baseline-7x.neon
- phpstan-baseline-8x.neon
- phpstan-baseline-by-php-version.php
- phpstan-baseline-standard.neon
- phpstan.neon
- src/Compat/ViewRenderer.php
- src/Control/PaginationControl.php
- src/FormElement/TermInput.php
phpstan is not run with an action anymore, as the action runs it its own docker container and hence has no access to files outside the repository root. A side-effect of this is, that phpstan now **really** runs with the php version set up by the matrix.
> phpstan: Streamline vendor file location with local dev-env

- src/Compat/StyleWithNonce.php
closes https://github.com/Icinga/icingaweb2-module-reporting/pull/228
> StyleWithNonce: Don't use `nonce` for cli commands

- asset/css/icons-base.less
> css: Use equal height for an icinga icon's `i` and `::before`

- asset/css/list/list-item.less
- src/Common/BaseItemList.php
It would be helpful if lists could perform additional tasks before and after a list item is added to it. Hence the events `BEFORE_ITEM_ADD` and `ON_ITEM_ADD` would be desirable.
> BaseItemList: Emit events before and after adding the list item to the list

- src/Filter/Renderer.php
- tests/FilterTest.php
> Fix redundant filter operators

- asset/css/list/item-table.less
- src/Common/BaseTableRowItem.php
`content` collides with a container's content and confuses Icinga Web's JS (<2.12.2) which applies `impact` to it, but doesn't remove it sometimes.
> BaseTableRowItem: Use `column-content` as CSS class

- src/Common/BaseItemList.php
Currently, it is assumed that each list item in the list will be of same instance. Hence, calling `getItemClass()` method once in the `assemble()` method was sufficient to obtain the instance of the list item and build the entire list.
But if we want to build a list containing list items of different instances,  we would have to obtain the instance for each list item. For instance, the root problem list for dependencies contains host, service or redundancy group. Hence, the list item can be an instance of `HostListItem`, `ServiceListItem` or `RedundancyGroupListItem`.
In which case, it would require us to rewrite parent `assemble()` method, which is not desirable. To avoid this `createListItem()` method must be introduced, that will be responsible for creating the list item.
> Fetch item class for each row of the data

- src/Common/BaseItemList.php
To make the empty state message customizable for lists, we need setter/getter methods in `BaseItemList`
> BaseItemList: Add setter/getter to set empty state message

- src/Compat/SearchControls.php
This way we no longer have to set the suggestionUrl manually, as in (Host/Service)groupController
> SearchControls: Add available `$preserveParams` as default to `(SearchBar/SearchEditor)suggestionUrl`

- asset/css/controls.less
- asset/css/search-base.less
The `overflow-x: overlay` declaration is obsolete, since no browser (not even chrome) supports it anymore.
> SearchBar: Fix scrollbar position in default-layout controls

- src/Compat/CompatController.php
We recently separated filters from url parameters. Only `getQueryString()` renders both since then.
fixes #254
> CompatController: Patch tab extensions correctly again

- asset/css/search-base.less
- asset/css/variables.less
- asset/js/widget/TermInput.js
- src/FormElement/TermInput/TermContainer.php
This PR changes the way by which the user gets hinted about the possibility to remove an entry out of a read-only list of term-input values.
Resolves: https://github.com/Icinga/ipl-web/issues/243
> Display delete action when hovering over read-only term-input entries

- asset/css/search-base.less
- asset/js/widget/TermInput.js
- src/FormElement/TermInput/TermContainer.php
The remove label is now a title which allows terms to be as narrow as possible again.
justify-content which was previously used to center the label's contents cannot be used anymore though. It has the effect of pushing overflowing content
also to the left, which causes the icon to not be
centered at the minimum width. Plain old, but working, auto margins are the solution here.
fixes #256
> TermInput: Keep original minimum width of terms

- asset/css/item-layout.less
- asset/css/list/item-list.less
- asset/css/list/list-item.less
- asset/css/variables.less
- src/Common/BaseItemList.php
- src/Common/BaseListItem.php
- src/Common/BaseOrderedItemList.php
- src/Common/BaseOrderedListItem.php
- src/Common/ItemRenderer.php
- src/Layout/DetailedItemLayout.php
- src/Layout/HeaderItemLayout.php
- src/Layout/ItemLayout.php
- src/Layout/MinimalItemLayout.php
- src/Widget/ItemList.php
- src/Widget/ListItem.php
Represents mostly what was already part of Icinga DB Web in the form of view modes. The important change is that what was previously list layout, is now just item layout.
Allowing the re-use of the same implementation of any given layout in a list or list-like container, but also in any other, e.g. a detail header.
Just implement a renderer for a particular item type and couple it with the desired layout. Add the result to your list item, header, flyout, whatever and… you're done!
> Introduce new item list/header layout implementation

- asset/css/balls.less
Remove 'display: block' from state ball icons to avoid icons moving to the top.
Refs https://github.com/Icinga/icingadb-web/issues/1042
> Remove 'display: block' from state ball icons

- src/Control/PaginationControl.php
By following a link a user got from someone, the resulting entries might be fewer than previously and hence the list will also be empty.
If there is only a single page, the control didn't provide any option to switch to it until now.
Now a simple link allows to clear the page parameter.
fixes #267
> Provide a way to go back to the first page in case the current page is empty

- src/Widget/ItemList.php
Since there are no comments, `$paginationControl->getEmptyStateMessage()` returns `null` and passes this to `ObjectList`, which converts the null to a `ipl/Html/Text` instance, resulting in a missing default message.
> ItemList: Don't convert `null` to Html

- asset/css/item-layout.less
Reduce the caption from **two** lines to **one** line in the default item layout.
> Limit default item layout caption to one line

- asset/css/item-layout.less
And remove the superfluous max-height because line-clamp already limits the height.
Fixes #279
> Set line-clamp to 5

- asset/css/empty-state.less
- asset/css/list/item-list.less
- asset/css/list/item-table.less
- src/Widget/ItemList.php
Use `EmptyState` instead of`EmptyStateBar` in `ItemList` but keep rendering it as as `EmptyStateBar` if the list is the **main content**.
> Use empty state for item lists

- asset/css/compat.less
- asset/css/list/item-table.less
- src/Common/BaseTableRowItem.php
Followup of #253.
* Users of `\ipl\Web\Common\BaseTableRowItem` got weird results in the UI with it, which is fixed here.
* Icinga DB Web uses a custom layout that is based on the old item table layout. Quick fixes are included here.
> Compatibility enhancements

- asset/js/widget/TermInput.js
Previously, the first click of submit button in a form with with the term input was triggering an auto submit, instead of submitting the form. This fix resolves it.
**Before**:
https://github.com/user-attachments/assets/de4964ef-c7cb-47f1-8986-e17db8066f07
**After**:
https://github.com/user-attachments/assets/64bce31f-231e-43d2-802d-9b571713144c
> Clicking submit button should submit the form with term input

- asset/css/item-layout.less
In the minimal view mode in item lists, the check output is not properly aligned vertically with the remaining text, it's baseline is slightly too high. This is because the header is a **flexbox** with `align-items: flex-start`. Setting `align-items: baseline` did increase the total `height` of the header from `18px` to `19px`. This is not what we want and would affect the control layout in the detail area of an object.
To solve this we have to set the header's height to fixed `1.5em`. The `align-items: baseline` now aligns the texts without increasing the `height`.
Fixes https://github.com/Icinga/icingadb-web/issues/785
> Align title and caption text in minimal layout

- asset/css/compat.less
- asset/css/suggestion-element.less
- asset/css/variables.less
- src/FormElement/SuggestionElement.php
Requires https://github.com/Icinga/ipl-html/pull/148
> Introduce `SuggestionElement`

- composer.json
- src/Control/SortControl.php
The event is not being triggered anymore if the form has been sent.
Requires https://github.com/Icinga/ipl-html/pull/153
> SortControl: Do not check form transmission on request anymore
