src/Control/SortControl.php

The button doesn't require the icinga form styles.

SortControl: Only apply class `icinga-controls` to the select

---

asset/css/controls.less
src/Control/PaginationControl.php

First shot on the implementation. Styling to be done.
Mockup here: https://github.com/Icinga/icingaweb2/issues/4111

Pagination control redesign

---

.github/workflows/php.yml
composer.json
phpunit.xml
src/Filter/ParseException.php
src/Filter/Parser.php
src/Filter/QueryString.php
src/Filter/Renderer.php
tests/FilterTest.php
tests/TestCase.php

Blocked by https://github.com/Icinga/ipl-stdlib/pull/15

Query String Filter

---

src/Common/CsrfCounterMeasure.php
src/Common/RedirectOption.php
src/Compat/CompatDecorator.php
src/Compat/CompatForm.php
src/FormDecorator/IcingaFormDecorator.php

Look at the commits please, they contain all details.

Form Utilities

---

src/Widget/Tabs.php

Applies the possibility to extend tabs extensions.

Implement tabs extend() method

---

asset/css/continue-with.less
asset/css/search-editor.less
src/Compat/CompatController.php
src/Widget/ContinueWith.php

Sneaked another two commits in :innocent:

Add `ContinueWith` widget

---

src/Common/FormUid.php
src/Control/SearchBar.php

refs https://github.com/Icinga/ipl-html/issues/45
blocked by https://github.com/Icinga/ipl-html/pull/48

Add `FormUid` trait

---

src/Control/LimitControl.php
src/Control/SortControl.php

Tool tip to LimitControl and SortControl is added to provide additional information to the user.
icinga/icingadb-web#144

Add tool tip to control items without label

---

src/Control/SearchBar.php
src/Control/SearchBar/Suggestions.php
src/Control/SearchBar/Terms.php
src/Control/SearchEditor.php
src/FormDecorator/IcingaFormDecorator.php

Requires https://github.com/Icinga/ipl-html/pull/51

Use strict ipl-html interfaces

---

asset/js/widget/FilterInput.js

Place group closings correctly in the searchbar's DOM

---

asset/css/search-bar.less

I thought, the margin was unnecessary.

CSS: Remove `.search-suggestions` offset.

---

asset/css/controls.less
src/Widget/ContinueWith.php

ContinueWith: Apply `.control-button` to content only

---

asset/js/widget/SearchBar.js

Related to https://github.com/Icinga/icingaweb2/pull/4538
fix https://github.com/Icinga/icingaweb2/issues/4525

SearchBar.js: Do not open multiple modal windows on multi click

---

asset/css/search-base.less
asset/js/widget/BaseInput.js
asset/js/widget/Completer.js
asset/js/widget/FilterInput.js
src/Filter/Renderer.php

Fix searchbar bugs

---

asset/js/notjQuery.js
asset/js/widget/BaseInput.js
asset/js/widget/Completer.js
asset/js/widget/FilterInput.js
src/Control/SearchBar/Suggestions.php

Searchbar UX improvements

---

asset/js/widget/BaseInput.js
asset/js/widget/Completer.js

Fix that search suggestions get hidden needlessly

---

src/Control/SearchBar.php
src/Control/SearchBar/ValidatedColumn.php
src/Control/SearchBar/ValidatedOperator.php
src/Control/SearchBar/ValidatedTerm.php
src/Control/SearchBar/ValidatedValue.php

Fix query string validation propagation

---

asset/css/search-editor.less
asset/css/variables.less
asset/css/vertical-key-value.less

This fixes issues for themes, especially high-contrast theme:
* horizontal/vertical-key-value colors
* searchbar-bg
* usage of disabled gray
See also [Icinga/icingaweb2/#4673](https://github.com/Icinga/icingaweb2/pull/4673)

css: fix theme issues

---

tests/FilterTest.php

FilterTest: Test what happens with empty chains next to siblings

---

src/Control/SearchBar/ValidatedOperator.php
src/Control/SearchEditor.php
src/Filter/Parser.php
src/Filter/QueryString.php
src/Filter/Renderer.php
tests/FilterTest.php

Required due to https://github.com/Icinga/ipl-stdlib/pull/34

Adjust usages of `ipl\Stdlib\Filter\Similar`

---

asset/css/awesome-icons.less
composer.json

resolves #71 
blocked by https://github.com/Icinga/icingaweb2/pull/4812

Upgrade to fontawesome 6.x

---

src/Compat/CompatController.php

They perfectly fit here, IMHO.

CompatController: Introduce db-web's `create...Control` methods

---

asset/css/controls.less
src/Control/SortControl.php

The `SortControl` had various dependencies to Icinga DB Web. These are now gone. Only Icinga Web 2 is still a requirement.

SortControl: Provide a more useful default layout/style

---

src/Control/SearchBar.php

SearchBar: Don't change `q`'s value during validation

---

src/FormDecorator/IcingaFormDecorator.php

IcingaFormDecorator: Don't wrap `SubmitButtonElements` in an empty `control-label-group` div

---

asset/css/search-editor.less
asset/css/variables.less

Make search editor errors visible again

---

src/FormElement/ScheduleElement.php

Do not autosubmit start with `NO_REPEAT` freq

---

src/Compat/CompatController.php

Not required by anything yet. Laid around too long in my stash though.

CompatController: Introduce method `sendExtraUpdates()`

---

src/Widget/IcingaIcon.php
src/Widget/Icon.php

https://github.com/Icinga/noma-web/pull/23

Make icon style adjustable

---

src/FormElement/ScheduleElement.php

Don't try access `interval` elem when `ANNUALLY` freq is selected

---

asset/css/balls.less
asset/css/variables.less

fixes https://github.com/Icinga/icingadb-web/issues/709

Add missing css variable and state-ball for state `unreachable`

---

asset/js/widget/BaseInput.js
src/FormElement/TermInput.php

Fix that `TermInput` entry removal resets focus

---

asset/css/icinga-icons.less

Add `grid` icinga icon

---

asset/js/widget/FilterInput.js
src/Common/StateBadges.php
src/Control/SearchBar/Suggestions.php
src/Filter/Parser.php
src/Filter/QueryString.php
src/Filter/Renderer.php
tests/FilterTest.php

Differentation between equal like unequal and unlike

---

asset/css/copy-to-clipboard.less
asset/js/widget/CopyToClipboard.js
src/Widget/CopyToClipboard.php

The button copies the text from the specified target id when mentioned otherwise it copies the text from the parent element.
ref Icinga/icingadb-web#677

Add copy to clipboard button widget

---

asset/css/state-badge.less
asset/css/variables.less

Add `state-none` state-badge

---

asset/css/balls.less

The name of the file doesn't get better and specificity is sometimes a bitch.

balls.less: Remove margin right of icons inside balls..

---

src/Control/SearchEditor.php

SearchEditor: Support new operators `~` and `!~`

---

src/Common/StateBadges.php
tests/StateBadgesTest.php

refs https://github.com/Icinga/icingadb-web/issues/795

StateBadges: Properly process base filters

---

asset/css/search-base.less

css: Define a foreground color for all suggestion text types

---

src/Common/StateBadges.php
src/Widget/StateBadge.php

refs https://github.com/Icinga/icingadb-web/pull/811

Deprecate `StateBadge` and `StateBadges`

---

asset/css/controls.less

css: Content following controls should not overlay them

---

asset/js/widget/Completer.js

fixes https://github.com/Icinga/icingaweb2-module-businessprocess/issues/408

Completer.js: Focus the selected item when selection starts

---

src/Widget/StateBadge.php

Reverts some of the changes made in 5f817a4

Undeprecate `StateBadge` class

---

phpstan-baseline.neon
src/FormElement/TermInput/TermSuggestions.php

blocked by https://github.com/Icinga/ipl-stdlib/pull/46

TermSuggestions: Use `ipl\Stdlib\yield_groups`

---

src/Compat/CompatController.php

CompatController: Properly define `X-Icinga-Location-Query`

---

asset/css/balls.less
asset/css/variables.less

This reverts commit 15fd6b6985fa53bf42a7d57c13bbb3d889de55af.

Revert "Add missing css variable and state-ball for state `unreachable`"

---

asset/js/widget/Completer.js

Completer.js: Include `X-Requested-With` in completion requests

---

src/Control/LimitControl.php
src/Control/PaginationControl.php

LimitControl: Reset page param to 1 if set

---

asset/js/iterator.js

Plus findKey[s] for working with maps.

js: Provide polyfills for iterator.map, .find and .filter

---

asset/css/list/item-table.less
src/Common/BaseItemTable.php
src/Common/BaseTableRowItem.php
src/Layout/DetailedItemTableLayout.php
src/Layout/ItemTableLayout.php
src/Layout/MinimalItemTableLayout.php
src/Widget/ItemTable.php
src/Widget/ItemTable/ItemTableRenderer.php
src/Widget/ItemTableRow.php

Basically the same as #252 but for `BaseItemTable` and `BaseTableRowItem`

Introduce new item table layout implementation

---

asset/css/balls.less
src/Widget/Ball.php
src/Widget/StateBall.php

Adds a proper PHP implementation for balls. Also changes the way text content is handled, as it is now done the same way as icons are.

Add class `ipl\Web\Widget\Ball`

---

src/Control/SortControl.php
tests/SortControlTest.php

Fix that the sort control ignores a default

---

src/Compat/SearchControls.php
src/Widget/ContinueWith.php

Fix that search controls do not preserve url filters

---

asset/css/item-layout.less

Icinga Notifications Web did that on its own previously. I think it's a good idea to support this natively.

item-layout.less: Support icons inside visuals

---

asset/css/list/item-list.less
asset/css/list/item-table.less

This reverts commit 64c8d6b4265665771a38182aeb94bb9267d5410a.
Host list Icinga DB Web:
Specificity is sometimes a bitch.

Revert "Remove redundant selectors"

---

asset/css/item-layout.less

item-layout: Don't let extended info shrink

---

src/Control/SearchBar/Suggestions.php

Form element names should always be a string.

Suggestions: Do not set null as ButtonElement name

---

asset/js/widget/BaseInput.js

BaseInput: Set the hidden input's value correctly on autosubmit

---

src/FormElement/TermInput.php

fixes #315 
requires https://github.com/Icinga/ipl-html/pull/171

TermInput: Sanitize container IDs properly
